In [50]:
import numpy as np
x = np.ravel(x)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [49]:
x = np.arange(0, 6, 0.5)
x = x.reshape(3, 4)
x

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [26]:
np.ndim([[1,2,3]])

2

In [27]:
np.shape([[1,2,3]])

(1, 3)

In [ ]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
np.empty([2,2])

array([[0., 0.],
       [0., 0.]])

np.zeros([2,3])

In [14]:
np.logspace(0, 1, 10, base=2)

array([1.        , 1.08005974, 1.16652904, 1.25992105, 1.36079   ,
       1.46973449, 1.58740105, 1.71448797, 1.85174942, 2.        ])

In [13]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
np.arange(0, 3, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8])

In [11]:
np.float16([1,2,3,4])

array([1., 2., 3., 4.], dtype=float16)

In [10]:
np.array([1,2,3,4], dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
import numpy as np